"""empty message

Revision ID: 031b80554824
Revises: 58f2df71e1a6
Create Date: 2022-06-19 10:31:37.291287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031b80554824'
down_revision = '58f2df71e1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_created_by_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'user', ['created_by'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_created_by_fkey', 'recipe', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###
