"""empty message

Revision ID: 26eab759d1d6
Revises: 4cd644763ad0
Create Date: 2022-06-21 14:59:22.837573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26eab759d1d6'
down_revision = '4cd644763ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_box', sa.Column('custom_meal_types', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_box', 'custom_meal_types')
    # ### end Alembic commands ###
