"""empty message

Revision ID: 4cd644763ad0
Revises: b5e47cb879d3
Create Date: 2022-06-21 13:54:51.829251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd644763ad0'
down_revision = 'b5e47cb879d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('vegetarian_freq', sa.SmallInteger(), nullable=True))
    op.drop_column('schedule', 'veg_freq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('veg_freq', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('schedule', 'vegetarian_freq')
    # ### end Alembic commands ###
