"""empty message

Revision ID: 58f2df71e1a6
Revises: 940413c07cb8
Create Date: 2022-06-17 14:34:49.712419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f2df71e1a6'
down_revision = '940413c07cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('average_cost_rating', sa.SmallInteger(), nullable=True))
    op.drop_column('recipe', 'fixed_schedule')
    op.drop_column('recipe', 'fixed_period')
    op.drop_column('recipe', 'scheduled')
    op.add_column('recipe_box', sa.Column('scheduled', sa.Boolean(), nullable=True))
    op.add_column('recipe_box', sa.Column('fixed_schedule', sa.Boolean(), nullable=True))
    op.add_column('recipe_box', sa.Column('fixed_period', sa.SmallInteger(), nullable=True))
    op.add_column('recipe_box', sa.Column('rating', sa.SmallInteger(), nullable=True))
    op.add_column('recipe_box', sa.Column('cost_rating', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_box', 'cost_rating')
    op.drop_column('recipe_box', 'rating')
    op.drop_column('recipe_box', 'fixed_period')
    op.drop_column('recipe_box', 'fixed_schedule')
    op.drop_column('recipe_box', 'scheduled')
    op.add_column('recipe', sa.Column('scheduled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('fixed_period', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('fixed_schedule', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('recipe', 'average_cost_rating')
    # ### end Alembic commands ###
