"""empty message

Revision ID: 6217f47b82e9
Revises: 031b80554824
Create Date: 2022-06-21 07:53:12.192239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6217f47b82e9'
down_revision = '031b80554824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'last_made')
    op.alter_column('recipe_box', 'scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('recipe_box', 'fixed_schedule',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe_box', 'fixed_schedule',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('recipe_box', 'scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('recipe', sa.Column('last_made', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
