"""empty message

Revision ID: 940413c07cb8
Revises: 6078a793c5e6
Create Date: 2022-06-17 10:46:23.005763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940413c07cb8'
down_revision = '6078a793c5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
