"""empty message

Revision ID: a2d7401947c9
Revises: 26eab759d1d6
Create Date: 2022-06-21 17:13:17.332817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d7401947c9'
down_revision = '26eab759d1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('meat_options', sa.String(length=30), nullable=False))
    op.alter_column('recipe', 'meal_types',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recipe', 'category')
    op.add_column('recipe_box', sa.Column('custom_meat_options', sa.String(length=30), nullable=False))
    op.alter_column('recipe_box', 'custom_meal_types',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe_box', 'custom_meal_types',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('recipe_box', 'custom_meat_options')
    op.add_column('recipe', sa.Column('category', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.alter_column('recipe', 'meal_types',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('recipe', 'meat_options')
    # ### end Alembic commands ###
