"""empty message

Revision ID: b5e47cb879d3
Revises: cbc08ca07064
Create Date: 2022-06-21 12:51:50.522572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e47cb879d3'
down_revision = 'cbc08ca07064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_box', sa.Column('schedule', sa.Boolean(), nullable=False))
    op.drop_column('recipe_box', 'scheduled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_box', sa.Column('scheduled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('recipe_box', 'schedule')
    # ### end Alembic commands ###
