"""empty message

Revision ID: cbc08ca07064
Revises: 6217f47b82e9
Create Date: 2022-06-21 07:59:14.573899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc08ca07064'
down_revision = '6217f47b82e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_box', sa.Column('last_made', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_box', 'last_made')
    # ### end Alembic commands ###
